name: Setup Geode CLI
description: Sets up Geode CLI

inputs:
  version:
    description: 'Which CLI version to use, defaults to latest release.'
    required: false
    default: latest

runs:
  using: "composite"
  steps:
    - name: Detect platform
      id: platform
      shell: bash
      run: |
        if [ "$RUNNER_OS" = "Linux" ]; then
          echo "host=linux" >> $GITHUB_OUTPUT
        elif [ "$RUNNER_OS" = "Windows" ]; then
          echo "host=win" >> $GITHUB_OUTPUT
        elif [ "$RUNNER_OS" = "macOS" ]; then
          echo "host=mac" >> $GITHUB_OUTPUT
        fi

    - name: Download Geode CLI
      uses: robinraju/release-downloader@v1
      with:
        repository: 'geode-sdk/cli'
        latest: ${{ inputs.version == 'latest' }}
        tag: ${{ inputs.version != 'latest' && inputs.version || '' }}
        fileName: '*-${{ steps.platform.outputs.host }}.zip'
        tarBall: false
        zipBall: false
        out-file-path: 'my-epic-geode-cli'

    - name: Setup Geode CLI
      shell: bash
      run: |
        7z x "my-epic-geode-cli/*-${{ steps.platform.outputs.host }}.zip" -omy-epic-geode-cli
        chmod +x my-epic-geode-cli/geode
        echo "$GITHUB_WORKSPACE/my-epic-geode-cli" >> $GITHUB_PATH
